#This workflow covers the following steps:
#1 Pre-processing ()of peak table generated from MS-DIAL
#2 Naming correction of GNPS output
#3 MS1 annotation with HMDB
#Step 1 and 2 are independent, Step 2 requires submission of GNPS export from MS-DIAL to GNPS
#The functions are modified from the original one to allow processing of single ion mode data and data without QC and blank.
#The workflow was adopted from https://github.com/respiratory-immunology-lab/metabolome-lipidome-MSDIAL/blob/main/instructions_v4.7.md

setwd('path_to_working_directory')
source('pmp_preprocess.R')
source('pmp_metab_isNamed.R')
source('gnps_format_names.R')
source('gnps_SE_names.R')
source('add_hmdb.R')
source('compare_annotations_met.R')
source('keep_annotated_met.R')
source('save_curation_table.R')
pos_output <- '...' #Set NULL if you do not have this mode ran, output from MS_DIAL has the name as "Height_x_xxxxxxxxx.txt", conversion to .csv file is required
neg_output <- NULL #Set NULL if you do not have this mode ran
metadata <- read.csv("path_to/metadata.csv", row.names = 1)

metab_pmp <- pmp_preprocess(pos_output, neg_output, metadata = metadata, samples_key = 'IMSCCS', intens_cols = 33:53,
                            info_cols = 1:32, pca_group = NULL, PCA_Title = NULL, blank_name = NULL, qc_name = "QC",
                            blankFC = 5, max_perc_mv = 0.8, missingPeaksFraction = 0.8, max_rsd = 25, 
                            mv_imp_rowmax = 0.7, mv_imp_colmax = 0.7, mv_imp_method = 'knn')

metab_pmp$PCA_plot # view the PCA plot
metab_pmp$glog_plot # confirm glog lambda value converged at the minima
metab_pmp$filtering_dimensions # view how feature/samples numbers decreased with filtering
pmp_metab_isNamed(metab_pmp$glog_results)

#The following starts with GNPS output, generated by submitting MS-DIAL GNPS export
# Import GNPS data
gnps_pos <- read_csv('path_to/Raw_height_table.csv')
gnps_neg <- NULL

# Format GNPS compound names and return a joined pos and neg data.frame
gnps <- gnps_format_names(gnps_pos_df = gnps_pos, gnps_neg_df = gnps_neg)

# Add the GNPS compound names to both the glog-transformed and imputed SE objects
rowData(metab_pmp$glog_results)$compound_name_gnps <- gnps_SE_names(gnps_df = gnps, 
                                                                          metab_SE = metab_pmp$glog_results)
#rowData(metab_pmp$imputed_results)$compound_name_gnps <- gnps_SE_names(gnps_df = gnps, metab_SE = metab_pmp$imputed_results)
hmdb_df <- readRDS('path_to/hmdb_metabolites_detect_quant_v5_20231102.rds') #acquired from https://github.com/respiratory-immunology-lab/metabolome-lipidome-MSDIAL/blob/main/hmdb_processing/hmdb_metabolites_detect_quant_v5_20231102.rds

# Search annotations in HMDB and add to the SE objects
metab_pmp$glog_results <- add_hmdb(metab_SE = metab_pmp$glog_results,
                                         hmdb = hmdb_df, mass_tol = 0.002, cores = 4)
#metab_pmp$imputed_results <- add_hmdb(metab_SE = metab_pmp$imputed_results,
#                                            hmdb = hmdb_df, mass_tol = 0.002, cores = 4)

# Prepare data.frame with alignment IDs and all four annotations and filter for at least one annotation
msdial_gnps_hmdb_glog <- compare_annotations_met(metab_pmp$glog_results)
#msdial_gnps_hmdb_imputed <- compare_annotations_met(metab_pmp$imputed_results)

# Keep only annotated rows and generate shortname column
metab_glog <- keep_annotated_met(metab_pmp$glog_results)
#metab_imputed <- keep_annotated_met(metab_pmp$imputed_results)

# Retrieve the shortname values
metab_shortnames <- rowData(metab_glog)$shortname

# Get HMDB and KEGG annotations
hmdb_annotations <- rowData(metab_glog)$HMDB
kegg_annotations <- rowData(metab_glog)$KEGG

# Save the curation table
save_curation_table(metab_glog, 'glog_curation.csv')
#save_curation_table(metab_imputed, 'imputed_curation.csv')

###Manual curation to pick good quality peaks

# Load quality data
metab_quality <- read_csv('path_to/glog_curation_manual_curated.csv')

#Back to MS-DIAL for manual curation for quality peaks.
#Create a column to insert tick boxes using spreadsheet software, check rows which are quality peaks (relies on personal judgement).
#Checked boxes will be converted into TRUE and can be used to filter the experimental object in the following line.
# Filter the features using the TRUE/FALSE quality_peak column
metab_glog <- metab_glog[metab_quality$quality_peak,]

#Save .rds
saveRDS(metab_glog, file = "annotated_qp.RDS") 
